apply from: 'gradle/scripts/helpers.gradle'

repositories {
    // Other repositories described by default:
    // CleanroomMC: https://maven.cleanroommc.com
    exclusiveContent {
        forRepository {
            maven {
                name 'CurseMaven'
                url 'https://cursemaven.com'
            }
        }
        filter {
            includeGroup 'curse.maven'
        }
    }

    ivy {
        url "https://google.com/404"
        ivyPattern "https://google.com/404"
        artifactPattern "https://mediafilez.forgecdn.net/files/[organisation]/[module]/[revision](-[classifier])(.[ext])"
        metadataSources {
            artifact()
        }
    }

    mavenLocal() // Must be last for caching to work
}

dependencies {
    implementation rfg.deobf("curse.maven:heat-and-climate-296096:4448881")
    // This is a local dependency.
    // It is not provided by Curse Maven, due to it is disallowed by its author.
    // Follow the guide of `localDependency/put_local_dependencies_here.txt`.
    implementation rfg.deobf("3940:469:HeatAndClimateLib_1.12.2-3.9.3")

    // JEI/HEI
    implementation rfg.deobf('curse.maven:had-enough-items-557549:4810661')

    // Debug tools
    // FTBLib and FTBUtilities are removed from CurseMaven by its author, changed to local dependencies.
    runtimeOnly files('localDependency/FTBLib-5.4.7.2.jar')
    runtimeOnly files('localDependency/FTBUtilities-5.4.1.131.jar')
}